// Copyright (c) 2024-2026 Daniel Krawisz
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#ifndef CRYPTO_MAC_CMAC
#define CRYPTO_MAC_CMAC

#include <crypto/cipher.hpp>
#include <crypto/block/cipher.hpp>
#include <crypto/block.hpp>
#include <crypto/MAC.hpp>

namespace crypto::MAC {

    template <typename Cipher, size_t key_size>
    requires (cipher::block::Cipher<Cipher, key_size>)
    struct CMAC {

        constexpr static size_t DigestSize = Cipher::BlockSize;

        CMAC (const cipher::symmetric_key<key_size> &key);

        CMAC &Update (const byte *b, size_t x);

        void Final (byte *mac);

        CMAC &Restart ();

    private:
        typename cipher::symmetric_key<key_size> Key;
        typename cipher::block::state<cipher::block::mode::CBC, DigestSize> CBC;
        byte Block[DigestSize];
        size_t Buffered; // number of bytes within Block that have been filled.
        byte_array<DigestSize> K1;
        byte_array<DigestSize> K2;

        static void Double (slice<byte, DigestSize> result, slice<const byte, DigestSize> input);
    };

}

namespace crypto {
    template <typename Cipher, size_t key_size>
    requires cipher::block::Cipher<Cipher, key_size>
    hash::digest<Cipher::BlockSize> inline CMAC (const cipher::symmetric_key<key_size> &key, byte_slice data) {
        return MAC::calculate<MAC::CMAC<Cipher, key_size>> (key, data);
    }

}

namespace crypto::MAC {

    template <typename Cipher, size_t key_size>
    requires cipher::block::Cipher<Cipher, key_size>
    CMAC<Cipher, key_size>::CMAC (const cipher::symmetric_key<key_size> &key):
        Key {key}, CBC {cipher::initialization_vector<DigestSize> {}}, Buffered {0} {
        byte zero[DigestSize] {};
        byte_array<DigestSize> L;

        Cipher::encrypt (L, Key, zero);

        Double (K1, L);
        Double (K2, K1);
    }

    template <typename Cipher, size_t key_size>
    requires cipher::block::Cipher<Cipher, key_size>
    CMAC<Cipher, key_size> &CMAC<Cipher, key_size>::Restart () {
        std::fill (CBC.IV.begin (), CBC.IV.end (), byte {0});
        Buffered = 0;
        return *this;
    }

    template <typename Cipher, size_t key_size>
    requires cipher::block::Cipher<Cipher, key_size>
    CMAC<Cipher, key_size> &CMAC<Cipher, key_size>::Update (
        const byte *b, size_t remaining) {

        while (remaining) {

            // If Block already contains a complete block, it cannot be the
            // final block anymore because there is more message data to process.
            // Encrypt it as the next CBC-MAC block before accepting more input.
            if (Buffered == DigestSize) {
                CBC.template encrypt<Cipher> (Block, Key, Block);
                Buffered = 0;
            }

            // Fill the pending block with as much input as possible.
            size_t n = std::min (DigestSize - Buffered, remaining);

            std::copy (b, b + n, Block + Buffered);

            Buffered += n;
            b += n;
            remaining -= n;
        }

        return *this;
    }

    template <typename Cipher, size_t key_size>
    requires cipher::block::Cipher<Cipher, key_size>
    void CMAC<Cipher, key_size>::Double (
        slice<byte, DigestSize> result,
        slice<const byte, DigestSize> input) {

        // CMAC subkeys are generated by doubling a value in GF(2^n).
        //
        // This is equivalent to shifting the entire block left by one bit.
        // If the most significant bit was set, the shift discards that bit
        // and the result must additionally be XORed with the reduction
        // polynomial constant Rb.
        //
        // For the 128-bit block size used by AES, Rb = 0x87.

        bool carry = (input[0] & 0x80) != 0;

        // Shift the block left by one bit, propagating each byte's high bit
        // into the low bit of the following byte.
        for (size_t i = 0; i < DigestSize; ++i) {
            byte next = (i + 1 < DigestSize) ? input[i + 1] : 0;

            result[i] = byte ((input[i] << 1) | (next >> 7));
        }

        // If the original value had its high bit set, reduce the result
        // modulo the field polynomial by XORing Rb into its low byte.
        if (carry)
            result[DigestSize - 1] ^= 0x87;

    }

    template <typename Cipher, size_t key_size>
    requires cipher::block::Cipher<Cipher, key_size>
    void CMAC<Cipher, key_size>::Final (byte mac[DigestSize]) {

        byte block[DigestSize];

        if (Buffered == DigestSize) {
            // The message ended exactly on a block boundary.
            //
            // The final complete message block is authenticated by XORing
            // it with K1 before the final block-cipher encryption.
            for (size_t i = 0; i < DigestSize; ++i)
                block[i] = Block[i] ^ K1[i];

        } else {
            // The final message block is incomplete (or the message is empty).
            //
            // CMAC pads it with a single 1 bit followed by zero bits, then
            // XORs the padded block with K2.
            for (size_t i = 0; i < Buffered; ++i)
                block[i] = Block[i];

            block[Buffered] = 0x80;

            for (size_t i = Buffered + 1; i < DigestSize; ++i)
                block[i] = 0;

            for (size_t i = 0; i < DigestSize; ++i)
                block[i] ^= K2[i];
        }

        // CBC chaining is applied to the final block. CBC currently contains
        // the chaining value resulting from all preceding message blocks.
        //
        // XOR the final prepared block with that chaining value, then encrypt
        // the result using the bare block-cipher encryption operation.
        for (size_t i = 0; i < DigestSize; ++i)
            block[i] ^= CBC.State[i];

        Cipher::encrypt (mac, Key, block);

    }

}

#endif

